// <auto-generated />
using System;
using Diary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327005019_updatedmigration")]
    partial class updatedmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diary.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the content of the first diary entry.",
                            CreatedOn = new DateTime(2026, 3, 27, 0, 50, 18, 970, DateTimeKind.Local).AddTicks(7347),
                            Disabled = false,
                            Enabled = true,
                            Title = "First Entry"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is the content of the second diary entry.",
                            CreatedOn = new DateTime(2026, 3, 27, 0, 50, 18, 970, DateTimeKind.Local).AddTicks(8706),
                            Disabled = false,
                            Enabled = true,
                            Title = "Second Entry"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is the content of the Third diary entry.",
                            CreatedOn = new DateTime(2026, 3, 27, 0, 50, 18, 970, DateTimeKind.Local).AddTicks(8713),
                            Disabled = false,
                            Enabled = true,
                            Title = "Third Entry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
