name: Build Dairy Docker Image

on:
  push:
    branches: [ "main" ]  # Trigger this whenever you push to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        cd Dairy
        docker build -t dairy-app-image:latest .
